// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	model "github.com/gotway/gotway/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CacheRepo is an autogenerated mock type for the CacheRepo type
type CacheRepo struct {
	mock.Mock
}

// DeleteCacheByPath provides a mock function with given fields: paths
func (_m *CacheRepo) DeleteCacheByPath(paths []model.CachePath) error {
	ret := _m.Called(paths)

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.CachePath) error); ok {
		r0 = rf(paths)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCacheByTags provides a mock function with given fields: tags
func (_m *CacheRepo) DeleteCacheByTags(tags []string) error {
	ret := _m.Called(tags)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCache provides a mock function with given fields: path, serviceKey
func (_m *CacheRepo) GetCache(path string, serviceKey string) (model.Cache, error) {
	ret := _m.Called(path, serviceKey)

	var r0 model.Cache
	if rf, ok := ret.Get(0).(func(string, string) model.Cache); ok {
		r0 = rf(path, serviceKey)
	} else {
		r0 = ret.Get(0).(model.Cache)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, serviceKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCacheDetail provides a mock function with given fields: path, serviceKey
func (_m *CacheRepo) GetCacheDetail(path string, serviceKey string) (model.CacheDetail, error) {
	ret := _m.Called(path, serviceKey)

	var r0 model.CacheDetail
	if rf, ok := ret.Get(0).(func(string, string) model.CacheDetail); ok {
		r0 = rf(path, serviceKey)
	} else {
		r0 = ret.Get(0).(model.CacheDetail)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, serviceKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreCache provides a mock function with given fields: cache, serviceKey
func (_m *CacheRepo) StoreCache(cache model.CacheDetail, serviceKey string) error {
	ret := _m.Called(cache, serviceKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.CacheDetail, string) error); ok {
		r0 = rf(cache, serviceKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
