// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShutdownHook is an autogenerated mock type for the ShutdownHook type
type ShutdownHook struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *ShutdownHook) Execute() {
	_m.Called()
}
