/*
MIT License

Copyright (c) 2021 Gotway

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gotway/gotway/pkg/kubernetes/crd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HTTPServiceLister helps list HTTPServices.
// All objects returned here must be treated as read-only.
type HTTPServiceLister interface {
	// List lists all HTTPServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HTTPService, err error)
	// HTTPServices returns an object that can list and get HTTPServices.
	HTTPServices(namespace string) HTTPServiceNamespaceLister
	HTTPServiceListerExpansion
}

// hTTPServiceLister implements the HTTPServiceLister interface.
type hTTPServiceLister struct {
	indexer cache.Indexer
}

// NewHTTPServiceLister returns a new HTTPServiceLister.
func NewHTTPServiceLister(indexer cache.Indexer) HTTPServiceLister {
	return &hTTPServiceLister{indexer: indexer}
}

// List lists all HTTPServices in the indexer.
func (s *hTTPServiceLister) List(selector labels.Selector) (ret []*v1alpha1.HTTPService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HTTPService))
	})
	return ret, err
}

// HTTPServices returns an object that can list and get HTTPServices.
func (s *hTTPServiceLister) HTTPServices(namespace string) HTTPServiceNamespaceLister {
	return hTTPServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HTTPServiceNamespaceLister helps list and get HTTPServices.
// All objects returned here must be treated as read-only.
type HTTPServiceNamespaceLister interface {
	// List lists all HTTPServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HTTPService, err error)
	// Get retrieves the HTTPService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.HTTPService, error)
	HTTPServiceNamespaceListerExpansion
}

// hTTPServiceNamespaceLister implements the HTTPServiceNamespaceLister
// interface.
type hTTPServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HTTPServices in the indexer for a given namespace.
func (s hTTPServiceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HTTPService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HTTPService))
	})
	return ret, err
}

// Get retrieves the HTTPService from the indexer for a given namespace and name.
func (s hTTPServiceNamespaceLister) Get(name string) (*v1alpha1.HTTPService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("httpservice"), name)
	}
	return obj.(*v1alpha1.HTTPService), nil
}
